### PR TITLE
adding ubuntu 14.04 support for rvm:passenger

### PR DESCRIPTION
**Pull request by jonoterc**
This also fixes https://github.com/maestrodev/puppet-rvm/issues/54

- passenger-install-apache2-module under Ubuntu 14.04 no longer generates passenger_extra.conf; skipping the copy step when this file is not present to copy
- adding an output file assertion to clarify passenger-install-apache2-module failures
- added Ubuntu 14.04 node set for testing (uses Ubuntu-supplied vagrant box)
- dropped the Ubuntu 13.10 testing nodeset as puppetlabs no longer provide a puppet release for saucy salamander
- tweaked some beaker indempotence assertions due to funny behavior with puppetlabs/apache (module dependency)
- passes beaker tests on Centos 6.4, 6.5, Debian 7, Ubuntu 12.04, and Ubuntu 14.04

### CODE REVIEW

**Comment by carlossg** [comment]
Thanks for the detailed description!

**Comment by jonoterc** [comment]
Thanks back to you for accepting that so quickly - any idea when you might be pushing a release to the forge?

**Comment by carlossg** [comment]
Released 1.9.0 now. Added a beaker ubuntu test using docker

**Comment by jonoterc** [comment]
Thanks!  Looks like its time for me to learn docker :)

**Pull request merged**
