### PR TITLE
see issue #76

### PR DESCRIPTION
**Pull request by edestecd**
Don't break compatibility with Darwin

### CODE REVIEW

**Comment by edestecd** [comment]
$::root_home fact from stdlib is causing the travis build to fail...
Does the travis build include stdlib?

**Comment by carlossg** [comment]
if gpg is ignored when not existing I'd do the same in the module, like in dfd306e
can you try it?

**Comment by edestecd** [comment]
I was trying to think of something like this as well.  I like the idea, but this fails on mac with this message:
Error: /Stage[main]/Main/Exec[system-rvm-gpg-key]: Could not evaluate: Could not find command 'gpg2'

I think puppet pre checks your commands and refuses to run them if they are not in the path.
It does this to make sure your path is set correctly.
I wonder if there is another way to check this.

**Comment by edestecd** [comment]
This may work:

```puppet
exec { 'system-rvm-gpg-key':
    command     => 'which gpg2 && gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3',
    path        => $::path,
    environment => ["HOME=${::root_home}"],
    unless      => 'which gpg2 && gpg2 --list-keys D39DC0E3',
    onlyif      => 'which gpg2',
}
```

**Comment by edestecd** [comment]
I tested the above on Darwin and Redhat 6.6 and it seems to work as desired.

**Comment by edestecd** [comment]
Pull request #78 implements this.

**Pull request closed without merging**
